Updated Ubuntu 20.04
Azure/azhpc-images pull request #81
Opened 2021-05-05 20:05 UTC by souvik-de

Updated HPCX to GCC 9.3.0 build; Updated HPCX path for sharpd; Using GCC 9.3.0 for MVAPICH2 and OMPI; Removed install_gcc script from install.sh in Ubuntu 20.04; Added NCCL config for users; Added WALinuxAgent; Disabled updates for Ubuntu 20.04; Moved disable_updates.sh to Ubuntu common directory; Disabled gcc 9.2.0 checking for Ubuntu 20.04 in Tests; Removed redundant root privileges; Updated ReadMe.

2021-05-05 22:57 UTC, jithinjosepkl requested changes

2021-05-05 22:57 UTC, jithinjosepkl commented on ubuntu/common/install_nccl.sh
> +NCCL_NET_GDR_LEVEL=5
Let's remove this - NCCL_NET_GDR_LEVEL=5

2021-05-05 22:57 UTC, jithinjosepkl commented on ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/README.md
> +    -x UCX_IB_PCI_RELAXED_ORDERING=on \
pls remove 

-x UCX_IB_PCI_RELAXED_ORDERING=on
-x NCCL_NET_GDR_LEVEL=5 

If you are adding UCX_TLS=tcp, please add the interface name also.

2021-05-05 22:57 UTC, jithinjosepkl commented on ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/hpc-tuning.sh
> +git clone https://github.com/longlimsft/WALinuxAgent.git
This will break if github.com/longlimsft/WALinuxAgent.git is updated. PLease use the main repository and cherry-pick the required commit.

2021-05-05 22:57 UTC, jithinjosepkl commented on ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/README.md
> +This Image is compliant with the Linux Kernel 5.4.0-1043-azure.
Is 20.04 also using 1043 kernel? please double check

2021-05-05 22:57 UTC, jithinjosepkl commented on ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/README.md
> +    -x UCX_IB_PCI_RELAXED_ORDERING=on \
same comments as above

2021-05-05 22:57 UTC, jithinjosepkl commented on ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/hpc-tuning.sh
> +git clone https://github.com/longlimsft/WALinuxAgent.git
same comment as above

2021-05-06 18:53 UTC, jithinjosepkl requested changes

2021-05-06 18:53 UTC, jithinjosepkl commented on ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/README.md
> +    -x UCX_TLS=tcp \
Needs to be removed. or add IF name

2021-05-06 18:53 UTC, jithinjosepkl commented on ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/README.md
> +    -x UCX_TLS=tcp \
Same comment as above

2021-05-06 18:53 UTC, jithinjosepkl commented on ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/hpc-tuning.sh
> +# Install WALinuxAgent
Move to common code?

2021-05-07 20:09 UTC, souvik-de commented on ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/README.md
> +    -x UCX_TLS=tcp \
-x NCCL_SOCKET_IFNAME=eth0 parameter exists !

2021-05-07 20:38 UTC, jithinjosepkl commented on ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/README.md
> +    -x UCX_TLS=tcp \
UCX interface is not added.

2021-05-07 20:45 UTC, souvik-de commented on ubuntu/ubuntu-18.x/ubuntu-18.04-hpc/README.md
> +    -x UCX_TLS=tcp \
Done

2021-05-07 20:45 UTC, souvik-de commented on ubuntu/ubuntu-20.x/ubuntu-20.04-hpc/README.md
> +    -x UCX_TLS=tcp \
Done

2021-05-07 22:48 UTC, jithinjosepkl approved these changes

2021-05-07 22:53 UTC, anshuljainansja approved these changes

2021-05-07 22:54 UTC, merged